Добавлен базовый api для frontend
AlekseyLobanov/django-todo pull request #19
Opened 2021-04-14 17:34 UTC by LazIvanS

2021-04-14 17:56 UTC, AlekseyLobanov requested changes
Довольно много пожеланий по стилю, которые, как мне кажется, стоит поправить.
Также нет поддержки ToDoItem, только списки. Эта поддержка нужна хоть какая-то, даже если методы будут просто заглушками, чтобы GUI можно было писать, опираясь на этот интерфейс

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +from json import loads, dumps
Такие импорты, в целом, плохая практика, особенно, на уровне не конечных модулей.
Лучше `import json`

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +import requests
Обычно, импорты принято сортировать по порядку: сначала стандартные и системные, потом библиотеки внешние, потом библиотеки внутренние потом какие-то проектные модули.

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +    def _authorised_(self, headers=JSON_HEADERS):
Лучше в принципе не использовать изменяемые аргументы как аргументы по умолчанию. Но если очень хочется, то можно использовать https://stackoverflow.com/a/52022425/1551213

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +get_api = lambda x: URL + "/" + x
Мне кажется, что слишком хитрая штука.
Для работы с url'ами следует использовать urljoin

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +class User(object):
Выбор имён мне кажется странным. 
У пользователя есть метод delete, который на самом деле удаляет какой-то список этого пользователя? Это надо как-то улучшить, мне кажется

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +CODE_SUCCESS = 200
1. Использование кодов возврата в Python мне кажется совсем не-идиоматичным. Функции делают то, что должно им делать. А если не получается, то кидают исключения
2. Этот код выдаётся наружу, но этот код, 200, не имеет смысла за пределами HTTP, что этот модуль должен, по идее, инкапуслировать
3. GET в случае успеха возвращает 200, но не другие методы: PUT,POST, DELETE

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +dump = lambda x: bytes(dumps(x), encoding="utf-8")
Вместо такого переопределения, мне кажется, лучше использовать `requests.get(json={"x":42})`, а он уже сам поставит правильные заголовки

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +        data = dump({"username": f"{user}", "password": f"{passwd}"})
```suggestion
        data = dump({"username": user, "password": passwd})
```

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +                data = loads(r.text)
```suggestion
                data = r.json()
```

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +            return r.status_code, data
Ещё раз напишу, что использование кодов возврата за пределами этого модуля будет плохой идеей, как мне кажется

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +    def auth(self, user, passwd):
В целом, токены JWT можно считать долгоживущими, поэтому их лучше получать только один раз, а потом
1. Уметь их принимать в конструкторе, чтобы пользователь смог только один раз ввести логин/пароль, а потом использовался бы готовый токен
2. В случае проблем пробовал бы получать новый токен.
3. Умел бы целиком работать без логина/пароля [опционально]
4. Не генерировать токенов на каждый запрос

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +    def __request__(func, verbose=True, **argv):
Использование методов с двойными подчёркиваниями является плохой практикой, т.к. обычно их для себя резервирует Python. Если это закрытый метод, то лучше использовать одинарное нижнее: `_do_somthing`

2021-04-14 17:56 UTC, AlekseyLobanov commented on frontend/api.py
> +URL = "http://127.0.0.1:8000"
Это точно нельзя хардкодить. Проще всего получать в конструкторе.

2021-04-14 18:06 UTC, AlekseyLobanov commented
А pre-commit хук точно отработал?

2021-04-15 09:36 UTC, LazIvanS commented on frontend/api.py
> +from json import loads, dumps
Модуль весьма мал, плюс не то чтобы нам требовалось что-то большое от json, однако если поддерживать такой стиль по всему проекту то почему бы и исправить.

2021-04-15 09:36 UTC, LazIvanS commented on frontend/api.py
> +import requests
Сохранилось при переходе от urllib к requests

2021-04-15 09:36 UTC, LazIvanS commented on frontend/api.py
> +    def _authorised_(self, headers=JSON_HEADERS):
Ну искать какой-то специальный класс неизменяемого словаря (его именование уже об этом говорит), в принципе не выходящего за пределы своего модуля для одного аргумента не хотелось.

2021-04-15 09:36 UTC, LazIvanS commented on frontend/api.py
> +get_api = lambda x: URL + "/" + x
Не попалась по названию (при поиске аналога os.path.join), учтем

2021-04-15 09:36 UTC, LazIvanS commented on frontend/api.py
> +class User(object):
Выбор имен на данный момент целиком и полностью соответствует перечню запросов в swagger-е, вместе с развитием понятия что там реализовано будет и развитие документации-названий по тому что реализовано в API.

2021-04-15 09:37 UTC, LazIvanS commented on frontend/api.py
> +CODE_SUCCESS = 200
Про POST и остальные не учел. Добавлять их[коды] тоже не хотелось бы, но показать юзеру почему не проходит его запрос без залезания в код api тоже надо бы. Исключения тут уместными не казались, тк операция может не пройти именно на стороне сервера, но для лаконичности наверно придется общаться через них.

2021-04-15 09:37 UTC, LazIvanS commented on frontend/api.py
> +dump = lambda x: bytes(dumps(x), encoding="utf-8")
ок

2021-04-15 09:39 UTC, LazIvanS commented on frontend/api.py
> +    def auth(self, user, passwd):
Принимать в конструкторе токен звучит неплохо. А разве мы генерируем новые на каждый запрос? Проблемы с авторизацией это уже за пределами первой версии api.

2021-04-15 09:39 UTC, LazIvanS commented on frontend/api.py
> +    def __request__(func, verbose=True, **argv):
Да, привычка выделять, стоит использовать одинарные

2021-04-15 09:42 UTC, LazIvanS commented on frontend/api.py
> +URL = "http://127.0.0.1:8000"
Должно было быть в конструкторе

2021-04-15 11:07 UTC, AlekseyLobanov commented on frontend/api.py
> +    def auth(self, user, passwd):
Токены нигде не сохраняются, но каждый запрос этот токен требует. Значит генерируем новый токен на каждый запрос

2021-04-15 17:38 UTC, LazIvanS commented
Добавил исправления стиля, плюс базовое понимание того что происходит в запросах. Дальше уже пишем "удобные" методы работы со структурами данных, когда будет лучше понятна их структура

2021-04-17 10:42 UTC, AlekseyLobanov requested changes
Можно уточнить у коллег, но мне кажется, что текущий интерфейс требует изменений.
Если подумать, каким бы был клиент, если бы API уже было готово и было бы большим?
Мне кажется, что это сущности, с которыми мы работаем ApiList, ApiToDoItem (и другие, если бы они были) которые бы могли удаляться/создаваться/обновляться.
При этом они были бы как-то связаны непосредственно с настройками API (модуль-синглтон или отдельный класс), где под настройкой будет подразумеваться работа с транспортом HTTPS, json и JWT токенами.
Тогда эти сущности можно будет без изменений использовать на фронте или с минимальными изменениями.
Также удастся использовать мощную систему типов + возможно, typing

2021-04-17 10:42 UTC, AlekseyLobanov commented on frontend/api.py
> +    def __init__(self, url=DEFAULT_URL, token=None):
Тут мы говорим, что токен это словарь, т.е. как бы отказываемся от проверки типов. Типы нужны, чтобы их проверять. Я бы предложил принимать два токена: на доступ и на обновление (опционален). Тогда удастся использовать более жёсткие контракты без потери какой-либо гибкости

2021-04-17 10:42 UTC, AlekseyLobanov commented on frontend/api.py
> +        Delete list
Я придерживаюсь позиции, что лучше нормальные имена всегда, когда возможно, чем документация.
Также принято, что комментарии лучше использовать для ответа на вопрос "Зачем?", а не на вопрос "Что происходит?".
Например, переименовать
`     def delete(self, id):`
в 
`def delete_list(self, list_id)`
Заодно удастся избавиться от перекрытия имени `id`, что тоже не очень хорошо

2021-04-17 11:36 UTC, LazIvanS commented on frontend/api.py
> +        Delete list
Это имя соответствует запросу из сваггера, более того то что делает этот запрос это все еще догадка

2021-04-17 11:37 UTC, LazIvanS commented on frontend/api.py
> +    def __init__(self, url=DEFAULT_URL, token=None):
Предполагается что юзер не знает об апи и формате токенов и пользуется только теми токенами что оно ему предоставляет. Но немного больше логики - да, можно

2021-04-17 11:39 UTC, LazIvanS commented
Текущие запросы в апи - ниузкоуровневые, 1-1 запросы. Тогда добавлю систему классов для работы с более высокоуровневыми командами.

2021-04-22 17:40 UTC, closed without merging